# Generated by Django 3.2 on 2021-04-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_domain_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='image',
            field=models.ImageField(default='/static/lady-in-yoga.jpg', upload_to='images'),
        ),
    ]
