# Generated by Django 3.2 on 2021-04-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_domai'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domai',
        ),
    ]
